fname = input("Enter your First Name: ")
lname = input("Enter your Last Name: ")
mname = input("Enter your Middle Name: ")
bday = input("Enter your Birthday: ")
gender = input("Enter your Gender: ")
address = input("Enter your Address: ")
course = input("Enter your Course: ")
ylevel = input("Enter your Year Level: ")

print("")
print("Personal Information:")
print("First Name: ", fname)
print("Middle Name: ", mname)
print("Last Name: ", lname)
print("Birthday: ", bday)
print("Gender: ", gender)
print("Address: ", address)
print("Course: ", course)
print("Year Level: ", ylevel)